package com.model;

import com.base.BaseModel;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sys_area
 * @mbg.generated do_not_delete_during_merge
 */
public class SysArea extends BaseModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_area.Area_ID
     * @mbg.generated
     */
    private String areaId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_area.Area_Name
     * @mbg.generated
     */
    private String areaName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_area.Short_Name
     * @mbg.generated
     */
    private String shortName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_area.Father_Area_ID
     * @mbg.generated
     */
    private String fatherAreaId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_area.Area_Code
     * @mbg.generated
     */
    private String areaCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_area.AddTime
     * @mbg.generated
     */
    private Date addtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_area.UpdateTime
     * @mbg.generated
     */
    private Date updatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_area.Sort_ID
     * @mbg.generated
     */
    private Integer sortId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_area.FullName
     * @mbg.generated
     */
    private String fullname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_area.Area_ID
     *
     * @return the value of sys_area.Area_ID
     * @mbg.generated
     */
    public String getAreaId() {
        return areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_area.Area_ID
     *
     * @param areaId the value for sys_area.Area_ID
     * @mbg.generated
     */
    public void setAreaId(String areaId) {
        this.areaId = areaId == null ? null : areaId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_area.Area_Name
     *
     * @return the value of sys_area.Area_Name
     * @mbg.generated
     */
    public String getAreaName() {
        return areaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_area.Area_Name
     *
     * @param areaName the value for sys_area.Area_Name
     * @mbg.generated
     */
    public void setAreaName(String areaName) {
        this.areaName = areaName == null ? null : areaName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_area.Short_Name
     *
     * @return the value of sys_area.Short_Name
     * @mbg.generated
     */
    public String getShortName() {
        return shortName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_area.Short_Name
     *
     * @param shortName the value for sys_area.Short_Name
     * @mbg.generated
     */
    public void setShortName(String shortName) {
        this.shortName = shortName == null ? null : shortName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_area.Father_Area_ID
     *
     * @return the value of sys_area.Father_Area_ID
     * @mbg.generated
     */
    public String getFatherAreaId() {
        return fatherAreaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_area.Father_Area_ID
     *
     * @param fatherAreaId the value for sys_area.Father_Area_ID
     * @mbg.generated
     */
    public void setFatherAreaId(String fatherAreaId) {
        this.fatherAreaId = fatherAreaId == null ? null : fatherAreaId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_area.Area_Code
     *
     * @return the value of sys_area.Area_Code
     * @mbg.generated
     */
    public String getAreaCode() {
        return areaCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_area.Area_Code
     *
     * @param areaCode the value for sys_area.Area_Code
     * @mbg.generated
     */
    public void setAreaCode(String areaCode) {
        this.areaCode = areaCode == null ? null : areaCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_area.AddTime
     *
     * @return the value of sys_area.AddTime
     * @mbg.generated
     */
    public Date getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_area.AddTime
     *
     * @param addtime the value for sys_area.AddTime
     * @mbg.generated
     */
    public void setAddtime(Date addtime) {
        this.addtime = addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_area.UpdateTime
     *
     * @return the value of sys_area.UpdateTime
     * @mbg.generated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_area.UpdateTime
     *
     * @param updatetime the value for sys_area.UpdateTime
     * @mbg.generated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_area.Sort_ID
     *
     * @return the value of sys_area.Sort_ID
     * @mbg.generated
     */
    public Integer getSortId() {
        return sortId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_area.Sort_ID
     *
     * @param sortId the value for sys_area.Sort_ID
     * @mbg.generated
     */
    public void setSortId(Integer sortId) {
        this.sortId = sortId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_area.FullName
     *
     * @return the value of sys_area.FullName
     * @mbg.generated
     */
    public String getFullname() {
        return fullname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_area.FullName
     *
     * @param fullname the value for sys_area.FullName
     * @mbg.generated
     */
    public void setFullname(String fullname) {
        this.fullname = fullname == null ? null : fullname.trim();
    }
}