package com.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class SysAreaCriteria {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_area
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_area
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_area
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_area
     * @mbg.generated
     */
    public SysAreaCriteria() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_area
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_area
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_area
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_area
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_area
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_area
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_area
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_area
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_area
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_area
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andAreaNameIsNull() {
            addCriterion("area_name is null");
            return (Criteria) this;
        }

        public Criteria andAreaNameIsNotNull() {
            addCriterion("area_name is not null");
            return (Criteria) this;
        }

        public Criteria andAreaNameEqualTo(String value) {
            addCriterion("area_name =", value, "areaName");
            return (Criteria) this;
        }

        public Criteria andAreaNameNotEqualTo(String value) {
            addCriterion("area_name <>", value, "areaName");
            return (Criteria) this;
        }

        public Criteria andAreaNameGreaterThan(String value) {
            addCriterion("area_name >", value, "areaName");
            return (Criteria) this;
        }

        public Criteria andAreaNameGreaterThanOrEqualTo(String value) {
            addCriterion("area_name >=", value, "areaName");
            return (Criteria) this;
        }

        public Criteria andAreaNameLessThan(String value) {
            addCriterion("area_name <", value, "areaName");
            return (Criteria) this;
        }

        public Criteria andAreaNameLessThanOrEqualTo(String value) {
            addCriterion("area_name <=", value, "areaName");
            return (Criteria) this;
        }

        public Criteria andAreaNameLike(String value) {
            addCriterion("area_name like", value, "areaName");
            return (Criteria) this;
        }

        public Criteria andAreaNameNotLike(String value) {
            addCriterion("area_name not like", value, "areaName");
            return (Criteria) this;
        }

        public Criteria andAreaNameIn(List<String> values) {
            addCriterion("area_name in", values, "areaName");
            return (Criteria) this;
        }

        public Criteria andAreaNameNotIn(List<String> values) {
            addCriterion("area_name not in", values, "areaName");
            return (Criteria) this;
        }

        public Criteria andAreaNameBetween(String value1, String value2) {
            addCriterion("area_name between", value1, value2, "areaName");
            return (Criteria) this;
        }

        public Criteria andAreaNameNotBetween(String value1, String value2) {
            addCriterion("area_name not between", value1, value2, "areaName");
            return (Criteria) this;
        }

        public Criteria andFatherIdIsNull() {
            addCriterion("father_id is null");
            return (Criteria) this;
        }

        public Criteria andFatherIdIsNotNull() {
            addCriterion("father_id is not null");
            return (Criteria) this;
        }

        public Criteria andFatherIdEqualTo(String value) {
            addCriterion("father_id =", value, "fatherId");
            return (Criteria) this;
        }

        public Criteria andFatherIdNotEqualTo(String value) {
            addCriterion("father_id <>", value, "fatherId");
            return (Criteria) this;
        }

        public Criteria andFatherIdGreaterThan(String value) {
            addCriterion("father_id >", value, "fatherId");
            return (Criteria) this;
        }

        public Criteria andFatherIdGreaterThanOrEqualTo(String value) {
            addCriterion("father_id >=", value, "fatherId");
            return (Criteria) this;
        }

        public Criteria andFatherIdLessThan(String value) {
            addCriterion("father_id <", value, "fatherId");
            return (Criteria) this;
        }

        public Criteria andFatherIdLessThanOrEqualTo(String value) {
            addCriterion("father_id <=", value, "fatherId");
            return (Criteria) this;
        }

        public Criteria andFatherIdLike(String value) {
            addCriterion("father_id like", value, "fatherId");
            return (Criteria) this;
        }

        public Criteria andFatherIdNotLike(String value) {
            addCriterion("father_id not like", value, "fatherId");
            return (Criteria) this;
        }

        public Criteria andFatherIdIn(List<String> values) {
            addCriterion("father_id in", values, "fatherId");
            return (Criteria) this;
        }

        public Criteria andFatherIdNotIn(List<String> values) {
            addCriterion("father_id not in", values, "fatherId");
            return (Criteria) this;
        }

        public Criteria andFatherIdBetween(String value1, String value2) {
            addCriterion("father_id between", value1, value2, "fatherId");
            return (Criteria) this;
        }

        public Criteria andFatherIdNotBetween(String value1, String value2) {
            addCriterion("father_id not between", value1, value2, "fatherId");
            return (Criteria) this;
        }

        public Criteria andAreaShortnameIsNull() {
            addCriterion("area_shortname is null");
            return (Criteria) this;
        }

        public Criteria andAreaShortnameIsNotNull() {
            addCriterion("area_shortname is not null");
            return (Criteria) this;
        }

        public Criteria andAreaShortnameEqualTo(String value) {
            addCriterion("area_shortname =", value, "areaShortname");
            return (Criteria) this;
        }

        public Criteria andAreaShortnameNotEqualTo(String value) {
            addCriterion("area_shortname <>", value, "areaShortname");
            return (Criteria) this;
        }

        public Criteria andAreaShortnameGreaterThan(String value) {
            addCriterion("area_shortname >", value, "areaShortname");
            return (Criteria) this;
        }

        public Criteria andAreaShortnameGreaterThanOrEqualTo(String value) {
            addCriterion("area_shortname >=", value, "areaShortname");
            return (Criteria) this;
        }

        public Criteria andAreaShortnameLessThan(String value) {
            addCriterion("area_shortname <", value, "areaShortname");
            return (Criteria) this;
        }

        public Criteria andAreaShortnameLessThanOrEqualTo(String value) {
            addCriterion("area_shortname <=", value, "areaShortname");
            return (Criteria) this;
        }

        public Criteria andAreaShortnameLike(String value) {
            addCriterion("area_shortname like", value, "areaShortname");
            return (Criteria) this;
        }

        public Criteria andAreaShortnameNotLike(String value) {
            addCriterion("area_shortname not like", value, "areaShortname");
            return (Criteria) this;
        }

        public Criteria andAreaShortnameIn(List<String> values) {
            addCriterion("area_shortname in", values, "areaShortname");
            return (Criteria) this;
        }

        public Criteria andAreaShortnameNotIn(List<String> values) {
            addCriterion("area_shortname not in", values, "areaShortname");
            return (Criteria) this;
        }

        public Criteria andAreaShortnameBetween(String value1, String value2) {
            addCriterion("area_shortname between", value1, value2, "areaShortname");
            return (Criteria) this;
        }

        public Criteria andAreaShortnameNotBetween(String value1, String value2) {
            addCriterion("area_shortname not between", value1, value2, "areaShortname");
            return (Criteria) this;
        }

        public Criteria andAreaFullnameIsNull() {
            addCriterion("area_fullname is null");
            return (Criteria) this;
        }

        public Criteria andAreaFullnameIsNotNull() {
            addCriterion("area_fullname is not null");
            return (Criteria) this;
        }

        public Criteria andAreaFullnameEqualTo(String value) {
            addCriterion("area_fullname =", value, "areaFullname");
            return (Criteria) this;
        }

        public Criteria andAreaFullnameNotEqualTo(String value) {
            addCriterion("area_fullname <>", value, "areaFullname");
            return (Criteria) this;
        }

        public Criteria andAreaFullnameGreaterThan(String value) {
            addCriterion("area_fullname >", value, "areaFullname");
            return (Criteria) this;
        }

        public Criteria andAreaFullnameGreaterThanOrEqualTo(String value) {
            addCriterion("area_fullname >=", value, "areaFullname");
            return (Criteria) this;
        }

        public Criteria andAreaFullnameLessThan(String value) {
            addCriterion("area_fullname <", value, "areaFullname");
            return (Criteria) this;
        }

        public Criteria andAreaFullnameLessThanOrEqualTo(String value) {
            addCriterion("area_fullname <=", value, "areaFullname");
            return (Criteria) this;
        }

        public Criteria andAreaFullnameLike(String value) {
            addCriterion("area_fullname like", value, "areaFullname");
            return (Criteria) this;
        }

        public Criteria andAreaFullnameNotLike(String value) {
            addCriterion("area_fullname not like", value, "areaFullname");
            return (Criteria) this;
        }

        public Criteria andAreaFullnameIn(List<String> values) {
            addCriterion("area_fullname in", values, "areaFullname");
            return (Criteria) this;
        }

        public Criteria andAreaFullnameNotIn(List<String> values) {
            addCriterion("area_fullname not in", values, "areaFullname");
            return (Criteria) this;
        }

        public Criteria andAreaFullnameBetween(String value1, String value2) {
            addCriterion("area_fullname between", value1, value2, "areaFullname");
            return (Criteria) this;
        }

        public Criteria andAreaFullnameNotBetween(String value1, String value2) {
            addCriterion("area_fullname not between", value1, value2, "areaFullname");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("`status` is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("`status` is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Byte value) {
            addCriterion("`status` =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Byte value) {
            addCriterion("`status` <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Byte value) {
            addCriterion("`status` >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Byte value) {
            addCriterion("`status` >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Byte value) {
            addCriterion("`status` <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Byte value) {
            addCriterion("`status` <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Byte> values) {
            addCriterion("`status` in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Byte> values) {
            addCriterion("`status` not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Byte value1, Byte value2) {
            addCriterion("`status` between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Byte value1, Byte value2) {
            addCriterion("`status` not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andUpdDatetimeIsNull() {
            addCriterion("upd_datetime is null");
            return (Criteria) this;
        }

        public Criteria andUpdDatetimeIsNotNull() {
            addCriterion("upd_datetime is not null");
            return (Criteria) this;
        }

        public Criteria andUpdDatetimeEqualTo(Date value) {
            addCriterion("upd_datetime =", value, "updDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdDatetimeNotEqualTo(Date value) {
            addCriterion("upd_datetime <>", value, "updDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdDatetimeGreaterThan(Date value) {
            addCriterion("upd_datetime >", value, "updDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdDatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("upd_datetime >=", value, "updDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdDatetimeLessThan(Date value) {
            addCriterion("upd_datetime <", value, "updDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdDatetimeLessThanOrEqualTo(Date value) {
            addCriterion("upd_datetime <=", value, "updDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdDatetimeIn(List<Date> values) {
            addCriterion("upd_datetime in", values, "updDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdDatetimeNotIn(List<Date> values) {
            addCriterion("upd_datetime not in", values, "updDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdDatetimeBetween(Date value1, Date value2) {
            addCriterion("upd_datetime between", value1, value2, "updDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdDatetimeNotBetween(Date value1, Date value2) {
            addCriterion("upd_datetime not between", value1, value2, "updDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdUserIsNull() {
            addCriterion("upd_user is null");
            return (Criteria) this;
        }

        public Criteria andUpdUserIsNotNull() {
            addCriterion("upd_user is not null");
            return (Criteria) this;
        }

        public Criteria andUpdUserEqualTo(String value) {
            addCriterion("upd_user =", value, "updUser");
            return (Criteria) this;
        }

        public Criteria andUpdUserNotEqualTo(String value) {
            addCriterion("upd_user <>", value, "updUser");
            return (Criteria) this;
        }

        public Criteria andUpdUserGreaterThan(String value) {
            addCriterion("upd_user >", value, "updUser");
            return (Criteria) this;
        }

        public Criteria andUpdUserGreaterThanOrEqualTo(String value) {
            addCriterion("upd_user >=", value, "updUser");
            return (Criteria) this;
        }

        public Criteria andUpdUserLessThan(String value) {
            addCriterion("upd_user <", value, "updUser");
            return (Criteria) this;
        }

        public Criteria andUpdUserLessThanOrEqualTo(String value) {
            addCriterion("upd_user <=", value, "updUser");
            return (Criteria) this;
        }

        public Criteria andUpdUserLike(String value) {
            addCriterion("upd_user like", value, "updUser");
            return (Criteria) this;
        }

        public Criteria andUpdUserNotLike(String value) {
            addCriterion("upd_user not like", value, "updUser");
            return (Criteria) this;
        }

        public Criteria andUpdUserIn(List<String> values) {
            addCriterion("upd_user in", values, "updUser");
            return (Criteria) this;
        }

        public Criteria andUpdUserNotIn(List<String> values) {
            addCriterion("upd_user not in", values, "updUser");
            return (Criteria) this;
        }

        public Criteria andUpdUserBetween(String value1, String value2) {
            addCriterion("upd_user between", value1, value2, "updUser");
            return (Criteria) this;
        }

        public Criteria andUpdUserNotBetween(String value1, String value2) {
            addCriterion("upd_user not between", value1, value2, "updUser");
            return (Criteria) this;
        }

        public Criteria andSortIdIsNull() {
            addCriterion("sort_id is null");
            return (Criteria) this;
        }

        public Criteria andSortIdIsNotNull() {
            addCriterion("sort_id is not null");
            return (Criteria) this;
        }

        public Criteria andSortIdEqualTo(Integer value) {
            addCriterion("sort_id =", value, "sortId");
            return (Criteria) this;
        }

        public Criteria andSortIdNotEqualTo(Integer value) {
            addCriterion("sort_id <>", value, "sortId");
            return (Criteria) this;
        }

        public Criteria andSortIdGreaterThan(Integer value) {
            addCriterion("sort_id >", value, "sortId");
            return (Criteria) this;
        }

        public Criteria andSortIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("sort_id >=", value, "sortId");
            return (Criteria) this;
        }

        public Criteria andSortIdLessThan(Integer value) {
            addCriterion("sort_id <", value, "sortId");
            return (Criteria) this;
        }

        public Criteria andSortIdLessThanOrEqualTo(Integer value) {
            addCriterion("sort_id <=", value, "sortId");
            return (Criteria) this;
        }

        public Criteria andSortIdIn(List<Integer> values) {
            addCriterion("sort_id in", values, "sortId");
            return (Criteria) this;
        }

        public Criteria andSortIdNotIn(List<Integer> values) {
            addCriterion("sort_id not in", values, "sortId");
            return (Criteria) this;
        }

        public Criteria andSortIdBetween(Integer value1, Integer value2) {
            addCriterion("sort_id between", value1, value2, "sortId");
            return (Criteria) this;
        }

        public Criteria andSortIdNotBetween(Integer value1, Integer value2) {
            addCriterion("sort_id not between", value1, value2, "sortId");
            return (Criteria) this;
        }

        public Criteria andMaxDelnumCountyIsNull() {
            addCriterion("max_delnum_county is null");
            return (Criteria) this;
        }

        public Criteria andMaxDelnumCountyIsNotNull() {
            addCriterion("max_delnum_county is not null");
            return (Criteria) this;
        }

        public Criteria andMaxDelnumCountyEqualTo(Byte value) {
            addCriterion("max_delnum_county =", value, "maxDelnumCounty");
            return (Criteria) this;
        }

        public Criteria andMaxDelnumCountyNotEqualTo(Byte value) {
            addCriterion("max_delnum_county <>", value, "maxDelnumCounty");
            return (Criteria) this;
        }

        public Criteria andMaxDelnumCountyGreaterThan(Byte value) {
            addCriterion("max_delnum_county >", value, "maxDelnumCounty");
            return (Criteria) this;
        }

        public Criteria andMaxDelnumCountyGreaterThanOrEqualTo(Byte value) {
            addCriterion("max_delnum_county >=", value, "maxDelnumCounty");
            return (Criteria) this;
        }

        public Criteria andMaxDelnumCountyLessThan(Byte value) {
            addCriterion("max_delnum_county <", value, "maxDelnumCounty");
            return (Criteria) this;
        }

        public Criteria andMaxDelnumCountyLessThanOrEqualTo(Byte value) {
            addCriterion("max_delnum_county <=", value, "maxDelnumCounty");
            return (Criteria) this;
        }

        public Criteria andMaxDelnumCountyIn(List<Byte> values) {
            addCriterion("max_delnum_county in", values, "maxDelnumCounty");
            return (Criteria) this;
        }

        public Criteria andMaxDelnumCountyNotIn(List<Byte> values) {
            addCriterion("max_delnum_county not in", values, "maxDelnumCounty");
            return (Criteria) this;
        }

        public Criteria andMaxDelnumCountyBetween(Byte value1, Byte value2) {
            addCriterion("max_delnum_county between", value1, value2, "maxDelnumCounty");
            return (Criteria) this;
        }

        public Criteria andMaxDelnumCountyNotBetween(Byte value1, Byte value2) {
            addCriterion("max_delnum_county not between", value1, value2, "maxDelnumCounty");
            return (Criteria) this;
        }

        public Criteria andMaxDelnumBaseIsNull() {
            addCriterion("max_delnum_base is null");
            return (Criteria) this;
        }

        public Criteria andMaxDelnumBaseIsNotNull() {
            addCriterion("max_delnum_base is not null");
            return (Criteria) this;
        }

        public Criteria andMaxDelnumBaseEqualTo(Byte value) {
            addCriterion("max_delnum_base =", value, "maxDelnumBase");
            return (Criteria) this;
        }

        public Criteria andMaxDelnumBaseNotEqualTo(Byte value) {
            addCriterion("max_delnum_base <>", value, "maxDelnumBase");
            return (Criteria) this;
        }

        public Criteria andMaxDelnumBaseGreaterThan(Byte value) {
            addCriterion("max_delnum_base >", value, "maxDelnumBase");
            return (Criteria) this;
        }

        public Criteria andMaxDelnumBaseGreaterThanOrEqualTo(Byte value) {
            addCriterion("max_delnum_base >=", value, "maxDelnumBase");
            return (Criteria) this;
        }

        public Criteria andMaxDelnumBaseLessThan(Byte value) {
            addCriterion("max_delnum_base <", value, "maxDelnumBase");
            return (Criteria) this;
        }

        public Criteria andMaxDelnumBaseLessThanOrEqualTo(Byte value) {
            addCriterion("max_delnum_base <=", value, "maxDelnumBase");
            return (Criteria) this;
        }

        public Criteria andMaxDelnumBaseIn(List<Byte> values) {
            addCriterion("max_delnum_base in", values, "maxDelnumBase");
            return (Criteria) this;
        }

        public Criteria andMaxDelnumBaseNotIn(List<Byte> values) {
            addCriterion("max_delnum_base not in", values, "maxDelnumBase");
            return (Criteria) this;
        }

        public Criteria andMaxDelnumBaseBetween(Byte value1, Byte value2) {
            addCriterion("max_delnum_base between", value1, value2, "maxDelnumBase");
            return (Criteria) this;
        }

        public Criteria andMaxDelnumBaseNotBetween(Byte value1, Byte value2) {
            addCriterion("max_delnum_base not between", value1, value2, "maxDelnumBase");
            return (Criteria) this;
        }

        public Criteria andTestBlobIsNull() {
            addCriterion("test_blob is null");
            return (Criteria) this;
        }

        public Criteria andTestBlobIsNotNull() {
            addCriterion("test_blob is not null");
            return (Criteria) this;
        }

        public Criteria andTestBlobEqualTo(String value) {
            addCriterion("test_blob =", value, "testBlob");
            return (Criteria) this;
        }

        public Criteria andTestBlobNotEqualTo(String value) {
            addCriterion("test_blob <>", value, "testBlob");
            return (Criteria) this;
        }

        public Criteria andTestBlobGreaterThan(String value) {
            addCriterion("test_blob >", value, "testBlob");
            return (Criteria) this;
        }

        public Criteria andTestBlobGreaterThanOrEqualTo(String value) {
            addCriterion("test_blob >=", value, "testBlob");
            return (Criteria) this;
        }

        public Criteria andTestBlobLessThan(String value) {
            addCriterion("test_blob <", value, "testBlob");
            return (Criteria) this;
        }

        public Criteria andTestBlobLessThanOrEqualTo(String value) {
            addCriterion("test_blob <=", value, "testBlob");
            return (Criteria) this;
        }

        public Criteria andTestBlobLike(String value) {
            addCriterion("test_blob like", value, "testBlob");
            return (Criteria) this;
        }

        public Criteria andTestBlobNotLike(String value) {
            addCriterion("test_blob not like", value, "testBlob");
            return (Criteria) this;
        }

        public Criteria andTestBlobIn(List<String> values) {
            addCriterion("test_blob in", values, "testBlob");
            return (Criteria) this;
        }

        public Criteria andTestBlobNotIn(List<String> values) {
            addCriterion("test_blob not in", values, "testBlob");
            return (Criteria) this;
        }

        public Criteria andTestBlobBetween(String value1, String value2) {
            addCriterion("test_blob between", value1, value2, "testBlob");
            return (Criteria) this;
        }

        public Criteria andTestBlobNotBetween(String value1, String value2) {
            addCriterion("test_blob not between", value1, value2, "testBlob");
            return (Criteria) this;
        }

        public Criteria andTestBooleanIsNull() {
            addCriterion("test_boolean is null");
            return (Criteria) this;
        }

        public Criteria andTestBooleanIsNotNull() {
            addCriterion("test_boolean is not null");
            return (Criteria) this;
        }

        public Criteria andTestBooleanEqualTo(Boolean value) {
            addCriterion("test_boolean =", value, "testBoolean");
            return (Criteria) this;
        }

        public Criteria andTestBooleanNotEqualTo(Boolean value) {
            addCriterion("test_boolean <>", value, "testBoolean");
            return (Criteria) this;
        }

        public Criteria andTestBooleanGreaterThan(Boolean value) {
            addCriterion("test_boolean >", value, "testBoolean");
            return (Criteria) this;
        }

        public Criteria andTestBooleanGreaterThanOrEqualTo(Boolean value) {
            addCriterion("test_boolean >=", value, "testBoolean");
            return (Criteria) this;
        }

        public Criteria andTestBooleanLessThan(Boolean value) {
            addCriterion("test_boolean <", value, "testBoolean");
            return (Criteria) this;
        }

        public Criteria andTestBooleanLessThanOrEqualTo(Boolean value) {
            addCriterion("test_boolean <=", value, "testBoolean");
            return (Criteria) this;
        }

        public Criteria andTestBooleanIn(List<Boolean> values) {
            addCriterion("test_boolean in", values, "testBoolean");
            return (Criteria) this;
        }

        public Criteria andTestBooleanNotIn(List<Boolean> values) {
            addCriterion("test_boolean not in", values, "testBoolean");
            return (Criteria) this;
        }

        public Criteria andTestBooleanBetween(Boolean value1, Boolean value2) {
            addCriterion("test_boolean between", value1, value2, "testBoolean");
            return (Criteria) this;
        }

        public Criteria andTestBooleanNotBetween(Boolean value1, Boolean value2) {
            addCriterion("test_boolean not between", value1, value2, "testBoolean");
            return (Criteria) this;
        }

        public Criteria andTestClobIsNull() {
            addCriterion("test_clob is null");
            return (Criteria) this;
        }

        public Criteria andTestClobIsNotNull() {
            addCriterion("test_clob is not null");
            return (Criteria) this;
        }

        public Criteria andTestClobEqualTo(String value) {
            addCriterion("test_clob =", value, "testClob");
            return (Criteria) this;
        }

        public Criteria andTestClobNotEqualTo(String value) {
            addCriterion("test_clob <>", value, "testClob");
            return (Criteria) this;
        }

        public Criteria andTestClobGreaterThan(String value) {
            addCriterion("test_clob >", value, "testClob");
            return (Criteria) this;
        }

        public Criteria andTestClobGreaterThanOrEqualTo(String value) {
            addCriterion("test_clob >=", value, "testClob");
            return (Criteria) this;
        }

        public Criteria andTestClobLessThan(String value) {
            addCriterion("test_clob <", value, "testClob");
            return (Criteria) this;
        }

        public Criteria andTestClobLessThanOrEqualTo(String value) {
            addCriterion("test_clob <=", value, "testClob");
            return (Criteria) this;
        }

        public Criteria andTestClobLike(String value) {
            addCriterion("test_clob like", value, "testClob");
            return (Criteria) this;
        }

        public Criteria andTestClobNotLike(String value) {
            addCriterion("test_clob not like", value, "testClob");
            return (Criteria) this;
        }

        public Criteria andTestClobIn(List<String> values) {
            addCriterion("test_clob in", values, "testClob");
            return (Criteria) this;
        }

        public Criteria andTestClobNotIn(List<String> values) {
            addCriterion("test_clob not in", values, "testClob");
            return (Criteria) this;
        }

        public Criteria andTestClobBetween(String value1, String value2) {
            addCriterion("test_clob between", value1, value2, "testClob");
            return (Criteria) this;
        }

        public Criteria andTestClobNotBetween(String value1, String value2) {
            addCriterion("test_clob not between", value1, value2, "testClob");
            return (Criteria) this;
        }

        public Criteria andAddUserIdIsNull() {
            addCriterion("add_user_id is null");
            return (Criteria) this;
        }

        public Criteria andAddUserIdIsNotNull() {
            addCriterion("add_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andAddUserIdEqualTo(String value) {
            addCriterion("add_user_id =", value, "addUserId");
            return (Criteria) this;
        }

        public Criteria andAddUserIdNotEqualTo(String value) {
            addCriterion("add_user_id <>", value, "addUserId");
            return (Criteria) this;
        }

        public Criteria andAddUserIdGreaterThan(String value) {
            addCriterion("add_user_id >", value, "addUserId");
            return (Criteria) this;
        }

        public Criteria andAddUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("add_user_id >=", value, "addUserId");
            return (Criteria) this;
        }

        public Criteria andAddUserIdLessThan(String value) {
            addCriterion("add_user_id <", value, "addUserId");
            return (Criteria) this;
        }

        public Criteria andAddUserIdLessThanOrEqualTo(String value) {
            addCriterion("add_user_id <=", value, "addUserId");
            return (Criteria) this;
        }

        public Criteria andAddUserIdLike(String value) {
            addCriterion("add_user_id like", value, "addUserId");
            return (Criteria) this;
        }

        public Criteria andAddUserIdNotLike(String value) {
            addCriterion("add_user_id not like", value, "addUserId");
            return (Criteria) this;
        }

        public Criteria andAddUserIdIn(List<String> values) {
            addCriterion("add_user_id in", values, "addUserId");
            return (Criteria) this;
        }

        public Criteria andAddUserIdNotIn(List<String> values) {
            addCriterion("add_user_id not in", values, "addUserId");
            return (Criteria) this;
        }

        public Criteria andAddUserIdBetween(String value1, String value2) {
            addCriterion("add_user_id between", value1, value2, "addUserId");
            return (Criteria) this;
        }

        public Criteria andAddUserIdNotBetween(String value1, String value2) {
            addCriterion("add_user_id not between", value1, value2, "addUserId");
            return (Criteria) this;
        }

        public Criteria andAddUserIsNull() {
            addCriterion("add_user is null");
            return (Criteria) this;
        }

        public Criteria andAddUserIsNotNull() {
            addCriterion("add_user is not null");
            return (Criteria) this;
        }

        public Criteria andAddUserEqualTo(String value) {
            addCriterion("add_user =", value, "addUser");
            return (Criteria) this;
        }

        public Criteria andAddUserNotEqualTo(String value) {
            addCriterion("add_user <>", value, "addUser");
            return (Criteria) this;
        }

        public Criteria andAddUserGreaterThan(String value) {
            addCriterion("add_user >", value, "addUser");
            return (Criteria) this;
        }

        public Criteria andAddUserGreaterThanOrEqualTo(String value) {
            addCriterion("add_user >=", value, "addUser");
            return (Criteria) this;
        }

        public Criteria andAddUserLessThan(String value) {
            addCriterion("add_user <", value, "addUser");
            return (Criteria) this;
        }

        public Criteria andAddUserLessThanOrEqualTo(String value) {
            addCriterion("add_user <=", value, "addUser");
            return (Criteria) this;
        }

        public Criteria andAddUserLike(String value) {
            addCriterion("add_user like", value, "addUser");
            return (Criteria) this;
        }

        public Criteria andAddUserNotLike(String value) {
            addCriterion("add_user not like", value, "addUser");
            return (Criteria) this;
        }

        public Criteria andAddUserIn(List<String> values) {
            addCriterion("add_user in", values, "addUser");
            return (Criteria) this;
        }

        public Criteria andAddUserNotIn(List<String> values) {
            addCriterion("add_user not in", values, "addUser");
            return (Criteria) this;
        }

        public Criteria andAddUserBetween(String value1, String value2) {
            addCriterion("add_user between", value1, value2, "addUser");
            return (Criteria) this;
        }

        public Criteria andAddUserNotBetween(String value1, String value2) {
            addCriterion("add_user not between", value1, value2, "addUser");
            return (Criteria) this;
        }

        public Criteria andAddDttmIsNull() {
            addCriterion("add_dttm is null");
            return (Criteria) this;
        }

        public Criteria andAddDttmIsNotNull() {
            addCriterion("add_dttm is not null");
            return (Criteria) this;
        }

        public Criteria andAddDttmEqualTo(Date value) {
            addCriterionForJDBCDate("add_dttm =", value, "addDttm");
            return (Criteria) this;
        }

        public Criteria andAddDttmNotEqualTo(Date value) {
            addCriterionForJDBCDate("add_dttm <>", value, "addDttm");
            return (Criteria) this;
        }

        public Criteria andAddDttmGreaterThan(Date value) {
            addCriterionForJDBCDate("add_dttm >", value, "addDttm");
            return (Criteria) this;
        }

        public Criteria andAddDttmGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("add_dttm >=", value, "addDttm");
            return (Criteria) this;
        }

        public Criteria andAddDttmLessThan(Date value) {
            addCriterionForJDBCDate("add_dttm <", value, "addDttm");
            return (Criteria) this;
        }

        public Criteria andAddDttmLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("add_dttm <=", value, "addDttm");
            return (Criteria) this;
        }

        public Criteria andAddDttmIn(List<Date> values) {
            addCriterionForJDBCDate("add_dttm in", values, "addDttm");
            return (Criteria) this;
        }

        public Criteria andAddDttmNotIn(List<Date> values) {
            addCriterionForJDBCDate("add_dttm not in", values, "addDttm");
            return (Criteria) this;
        }

        public Criteria andAddDttmBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("add_dttm between", value1, value2, "addDttm");
            return (Criteria) this;
        }

        public Criteria andAddDttmNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("add_dttm not between", value1, value2, "addDttm");
            return (Criteria) this;
        }

        public Criteria andLastUpdUserIdIsNull() {
            addCriterion("last_upd_user_id is null");
            return (Criteria) this;
        }

        public Criteria andLastUpdUserIdIsNotNull() {
            addCriterion("last_upd_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andLastUpdUserIdEqualTo(String value) {
            addCriterion("last_upd_user_id =", value, "lastUpdUserId");
            return (Criteria) this;
        }

        public Criteria andLastUpdUserIdNotEqualTo(String value) {
            addCriterion("last_upd_user_id <>", value, "lastUpdUserId");
            return (Criteria) this;
        }

        public Criteria andLastUpdUserIdGreaterThan(String value) {
            addCriterion("last_upd_user_id >", value, "lastUpdUserId");
            return (Criteria) this;
        }

        public Criteria andLastUpdUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("last_upd_user_id >=", value, "lastUpdUserId");
            return (Criteria) this;
        }

        public Criteria andLastUpdUserIdLessThan(String value) {
            addCriterion("last_upd_user_id <", value, "lastUpdUserId");
            return (Criteria) this;
        }

        public Criteria andLastUpdUserIdLessThanOrEqualTo(String value) {
            addCriterion("last_upd_user_id <=", value, "lastUpdUserId");
            return (Criteria) this;
        }

        public Criteria andLastUpdUserIdLike(String value) {
            addCriterion("last_upd_user_id like", value, "lastUpdUserId");
            return (Criteria) this;
        }

        public Criteria andLastUpdUserIdNotLike(String value) {
            addCriterion("last_upd_user_id not like", value, "lastUpdUserId");
            return (Criteria) this;
        }

        public Criteria andLastUpdUserIdIn(List<String> values) {
            addCriterion("last_upd_user_id in", values, "lastUpdUserId");
            return (Criteria) this;
        }

        public Criteria andLastUpdUserIdNotIn(List<String> values) {
            addCriterion("last_upd_user_id not in", values, "lastUpdUserId");
            return (Criteria) this;
        }

        public Criteria andLastUpdUserIdBetween(String value1, String value2) {
            addCriterion("last_upd_user_id between", value1, value2, "lastUpdUserId");
            return (Criteria) this;
        }

        public Criteria andLastUpdUserIdNotBetween(String value1, String value2) {
            addCriterion("last_upd_user_id not between", value1, value2, "lastUpdUserId");
            return (Criteria) this;
        }

        public Criteria andLastUpdUserIsNull() {
            addCriterion("last_upd_user is null");
            return (Criteria) this;
        }

        public Criteria andLastUpdUserIsNotNull() {
            addCriterion("last_upd_user is not null");
            return (Criteria) this;
        }

        public Criteria andLastUpdUserEqualTo(String value) {
            addCriterion("last_upd_user =", value, "lastUpdUser");
            return (Criteria) this;
        }

        public Criteria andLastUpdUserNotEqualTo(String value) {
            addCriterion("last_upd_user <>", value, "lastUpdUser");
            return (Criteria) this;
        }

        public Criteria andLastUpdUserGreaterThan(String value) {
            addCriterion("last_upd_user >", value, "lastUpdUser");
            return (Criteria) this;
        }

        public Criteria andLastUpdUserGreaterThanOrEqualTo(String value) {
            addCriterion("last_upd_user >=", value, "lastUpdUser");
            return (Criteria) this;
        }

        public Criteria andLastUpdUserLessThan(String value) {
            addCriterion("last_upd_user <", value, "lastUpdUser");
            return (Criteria) this;
        }

        public Criteria andLastUpdUserLessThanOrEqualTo(String value) {
            addCriterion("last_upd_user <=", value, "lastUpdUser");
            return (Criteria) this;
        }

        public Criteria andLastUpdUserLike(String value) {
            addCriterion("last_upd_user like", value, "lastUpdUser");
            return (Criteria) this;
        }

        public Criteria andLastUpdUserNotLike(String value) {
            addCriterion("last_upd_user not like", value, "lastUpdUser");
            return (Criteria) this;
        }

        public Criteria andLastUpdUserIn(List<String> values) {
            addCriterion("last_upd_user in", values, "lastUpdUser");
            return (Criteria) this;
        }

        public Criteria andLastUpdUserNotIn(List<String> values) {
            addCriterion("last_upd_user not in", values, "lastUpdUser");
            return (Criteria) this;
        }

        public Criteria andLastUpdUserBetween(String value1, String value2) {
            addCriterion("last_upd_user between", value1, value2, "lastUpdUser");
            return (Criteria) this;
        }

        public Criteria andLastUpdUserNotBetween(String value1, String value2) {
            addCriterion("last_upd_user not between", value1, value2, "lastUpdUser");
            return (Criteria) this;
        }

        public Criteria andLastUpdDttmIsNull() {
            addCriterion("last_upd_dttm is null");
            return (Criteria) this;
        }

        public Criteria andLastUpdDttmIsNotNull() {
            addCriterion("last_upd_dttm is not null");
            return (Criteria) this;
        }

        public Criteria andLastUpdDttmEqualTo(Date value) {
            addCriterionForJDBCDate("last_upd_dttm =", value, "lastUpdDttm");
            return (Criteria) this;
        }

        public Criteria andLastUpdDttmNotEqualTo(Date value) {
            addCriterionForJDBCDate("last_upd_dttm <>", value, "lastUpdDttm");
            return (Criteria) this;
        }

        public Criteria andLastUpdDttmGreaterThan(Date value) {
            addCriterionForJDBCDate("last_upd_dttm >", value, "lastUpdDttm");
            return (Criteria) this;
        }

        public Criteria andLastUpdDttmGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("last_upd_dttm >=", value, "lastUpdDttm");
            return (Criteria) this;
        }

        public Criteria andLastUpdDttmLessThan(Date value) {
            addCriterionForJDBCDate("last_upd_dttm <", value, "lastUpdDttm");
            return (Criteria) this;
        }

        public Criteria andLastUpdDttmLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("last_upd_dttm <=", value, "lastUpdDttm");
            return (Criteria) this;
        }

        public Criteria andLastUpdDttmIn(List<Date> values) {
            addCriterionForJDBCDate("last_upd_dttm in", values, "lastUpdDttm");
            return (Criteria) this;
        }

        public Criteria andLastUpdDttmNotIn(List<Date> values) {
            addCriterionForJDBCDate("last_upd_dttm not in", values, "lastUpdDttm");
            return (Criteria) this;
        }

        public Criteria andLastUpdDttmBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("last_upd_dttm between", value1, value2, "lastUpdDttm");
            return (Criteria) this;
        }

        public Criteria andLastUpdDttmNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("last_upd_dttm not between", value1, value2, "lastUpdDttm");
            return (Criteria) this;
        }

        public Criteria andEnableIsNull() {
            addCriterion("`enable` is null");
            return (Criteria) this;
        }

        public Criteria andEnableIsNotNull() {
            addCriterion("`enable` is not null");
            return (Criteria) this;
        }

        public Criteria andEnableEqualTo(Boolean value) {
            addCriterion("`enable` =", value, "enable");
            return (Criteria) this;
        }

        public Criteria andEnableNotEqualTo(Boolean value) {
            addCriterion("`enable` <>", value, "enable");
            return (Criteria) this;
        }

        public Criteria andEnableGreaterThan(Boolean value) {
            addCriterion("`enable` >", value, "enable");
            return (Criteria) this;
        }

        public Criteria andEnableGreaterThanOrEqualTo(Boolean value) {
            addCriterion("`enable` >=", value, "enable");
            return (Criteria) this;
        }

        public Criteria andEnableLessThan(Boolean value) {
            addCriterion("`enable` <", value, "enable");
            return (Criteria) this;
        }

        public Criteria andEnableLessThanOrEqualTo(Boolean value) {
            addCriterion("`enable` <=", value, "enable");
            return (Criteria) this;
        }

        public Criteria andEnableIn(List<Boolean> values) {
            addCriterion("`enable` in", values, "enable");
            return (Criteria) this;
        }

        public Criteria andEnableNotIn(List<Boolean> values) {
            addCriterion("`enable` not in", values, "enable");
            return (Criteria) this;
        }

        public Criteria andEnableBetween(Boolean value1, Boolean value2) {
            addCriterion("`enable` between", value1, value2, "enable");
            return (Criteria) this;
        }

        public Criteria andEnableNotBetween(Boolean value1, Boolean value2) {
            addCriterion("`enable` not between", value1, value2, "enable");
            return (Criteria) this;
        }
    }

    /**
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}